---

- name: Cisco Enable password, Debug Var, msg
  hosts: cisco
  connection: network_cli
  gather_facts: false

  vars_files:
    - device_login_info.yml
#    - set_facts:
#        username: "{{ansible_user}}"
#        password: "{{ansible_pwd1}}"

  tasks:

  - name: Gather Login Information
    set_fact:
      connection:
        authorize: yes
        host: "{{ inventory_hostname }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_pwd }}"
        timeout: 20

#  - name: Ping
#    cisco.ios.ios_ping:
#       dest: all

#  - name: Get facts
#    debug:
#      var: ansible_facts

  - name: Show ip route output
    cisco.ios.ios_command:
#      provider: "{{ connection }}"
#     host: "{{ inventory_hostname }}"
#     username: "{{ ansible_user }}"
#     password: "{{ ansible_pwd }}" 
     commands: show ip int brief
    register: route_output

#   debug: msg "{{route_output}}"
  - name: show run
    ios_command:
      commands:
        - show run
        - show version
    register: config

  - name: save output to local directory
    copy:
      content: "{{ config.stdout | replace('\\n', '\n') }}"
      dest: "show-output/{{ inventory_hostname }}.ios"

  - name: Gather all facts
    cisco.ios.ios_facts:

  - name: Display version
    ansible.builtin.debug:
      msg: "The IOS version is: {{ ansible_net_version }}"

  - name: Display serial number
    ansible.builtin.debug:
      msg: "The serial number is:{{ ansible_net_serialnum }}"
