---

- hosts: cisco_routers
  gather_facts: false
  roles:
    - Juniper.junos
#  vars_files:
#    - device_login_info.yml
  vars:
    rtr_login:
      username: "{{ansible_user}}"
      password: "{{ansible_pwd1}}"
      host: "{{inventory_hostname}}"

    swt_login:
      username: "{{ansible_user}}"
      password: "{{ansible_pwd}}"
      host: "{{inventory_hostname}}"
#    - ansible_user: "{{ansible_user}}"
#    - ansible_ssh_pass: "{{ ansible_pwd1 }}"
# or ansible_pwd1 }}"
#    - host: "{{inventory_hostname}}"

  tasks:

      - set_facts:
          username: "{{ansible_user}}"
          password: "{{ansible_pwd1}}"

      - name: Gather router facts
        cisco.ios.ios_facts:

      - name: Gather only the config and default facts
        ios_facts:
          gather_subset:
            - config

      - name: Run multiple commands on remote nodes
        cisco.ios.ios_command:
          commands:
            - show version
            - show ip int brief
#        - result[0] contains IOS
#        - result[1] contains Loopback0
#    vars:
#      ansible_command_timeout: 60

      - name: Display version
        ansible.builtin.debug:
          msg: "The IOS version is: {{ ansible_net_version }}"

      - name: Display serial number
        ansible.builtin.debug:
          msg: "The serial number is:{{ ansible_net_serialnum }}"
