---
- hosts: cisco
  connection: network_cli
  gather_facts: false


  tasks:
    - name: Show ip route output
      ios_command:
        commands: show ip route
#        username: "mdalzi"
#        password: "Zanouba@@1978$$"
      register: route_output
