
---
- name: Get Device Facts
  hosts: junos
  connection: local
  gather_facts: no




#- name: Enable NETCONF
#  hosts: junos
#  connection: ansible.netcommon.network_cli
#  junipernetworks.junos.junos_netconf:
#  when: ansible_network_os == 'junipernetworks.junos.junos'
