
---
- name: Get Device Facts
  hosts: junos
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos

  vars_prompt:
  - name: USERNAME
    prompt: user name
    private: no
  - name: DEVICE_PASSWORD
    prompt: Device password
    private: yes

  tasks:
  - name: Get device facts
    juniper_junos_facts:
      savedir: "{{ playbook_dir }}"
      user: "{{ USERNAME }}"
      passwd: "{{ DEVICE_PASSWORD }}"
